# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
maven_group = com.ssblur
archives_name = template
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.1.1

# JVM properties
jvm_version=25
kotlin_version=2.3.20

# Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.146.1+26.1.2
neoforge_version=26.1.1.15-beta
kff_version=6.2.0
flk_version=1.13.10+kotlin.2.3.20
unfocused_version=0.3.0-26.1.1
