# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
maven_group = com.ssblur
archives_name = template
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# JVM properties
jvm_version=21
kotlin_version=2.1.21

# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.116.9+1.21.1
neoforge_version=21.1.194
kff_version=5.11.0
flk_version=1.13.10+kotlin.2.3.20
unfocused_version=0.3.6-1.21.1

jei_version=19.21.0.247
emi_version=1.1.22+1.21.1
